### ISSUE TITLE
Map Lag and Tanking Frame Rates

### ISSUE THREAD

**Issue by zaklyles** [kemayo/wow-handynotes-warwithin#13]
Basically, the issue I've been experiencing is opening the map, particularly in Ringing Deeps and Hallowfall, would take 3-5 seconds for the map to load.  I was also experiencing horrible lag spikes, with very choppy frame rates while flying in Ringing Deeps and Hallowfall.  At first I didn't associate the two with one another.

Today, I decided to do process of elimination, and found that this addon was causing both the map lag and the frame rates to drop.

If I login but do not open the map, I can fly around without any framerate issues.  But once I open the map and the handy notes data for this addon load, flying becomes very choppy and framerates drop down to sometimes low 20's.  With the addon disabled, I get an average of 60-105 fps.

I'm on a Ryzen 5600x, with a GeForce 4070 Super and 2TB NVMe SSD.

**Comment by kemayo** [comment]
Interesting -- there's presumably something more going on, because I don't see that effect. I *do* experience an almost imperceptible stutter when the map opens, and see a maybe 5fps hit to framerate when it's open. You have a noticeably higher-spec PC than I do currently, so I'd expect it to be worse for me than for you.

With that said... could you try a few things and let me know if they have any impact:

![image](https://github.com/user-attachments/assets/ce083857-c8b7-40ad-9d67-9fc01e23525a)

* turn off "show routes"
* turn off showing NPCs
* turn off showing treasure

**Comment by zaklyles** [comment]
Ok, seems like it's an issue with Dugi Questing Essentials.  Went through one by one again, starting with only HandyNotes and TWW Treasures and Rares, no map lag, no frame rate issues.  As soon as I enabled Dugi, boom, problem returned.

With Dugi disabled, there are zero lag issues, zero stutter/frame loss when flying.

**Comment by kemayo** [comment]
Good to know! Thanks for following up to let me know the cause.
