### ISSUE TITLE
Treasure's Showing When They Shouldn't??

### ISSUE THREAD

**Issue by aus10code** [kemayo/wow-handynotes-warwithin#6]
![image](https://github.com/user-attachments/assets/0a2b4e50-efea-41e6-9ba3-9f12bd8a2b45)
![image](https://github.com/user-attachments/assets/179d170f-da79-405b-95b2-90cfd241aa9b)

Why are these 2 treasure icons showing if I have already found the items on other characters?

Maybe this is a user error and I'm missing a setting.

Thanks in advance for help.

**Comment by kemayo** [comment]
It shows because it's still lootable for the current character (it can tell because you haven't completed the associated quest), and so there's still a reward there for you if you go grab it.

Right now there's not a way to tell it to ignore that, but I'm planning on expanding the options a bit so that the same "notable" concept that applies to rares can also apply to treasures, at which point something like this where you already have the transmog it contains could just be filtered out.

**Comment by aus10code** [comment]
> Right now there's not a way to tell it to ignore that, but I'm planning on expanding the options a bit so that the same "notable" concept that applies to rares can also apply to treasures, at which point something like this where you already have the transmog it contains could just be filtered out.

That would be awesome. Thanks for the swift reply

**Comment by kemayo** [comment]
I've put an alpha up on curse that lets this happen. If you try it, going into the menu and saying that only notable treasures should be shown will make it so that only treasures that have something you don't yet know in them will appear.

**Comment by aus10code** [comment]
![image](https://github.com/user-attachments/assets/06075ffd-d4bf-4bba-9439-e2bf6649b9fc)
![image](https://github.com/user-attachments/assets/6558af9c-c7b1-4134-a186-ffb0975da5d9)
![image](https://github.com/user-attachments/assets/e71e384b-68ce-4be7-9d3e-d365f1fd8df6)

I am a new user but from what I can tell, this seems to be exactly what I was looking for. I will keep you posted if anymore ideas/concerns arise!

**Comment by kemayo** [comment]
Excellent, I'm glad it worked for you!
